include: EasyjetHub/base-config.yaml

do_CP_systematics: false

### tagging jets vs RNN strategy
### false: select tagging jets ---> higgs candidate jets
### true : select higgs candidate jets ---> load VBF-RNN
UseVBFRNN : false

# Toggles for object types
do_muons: true
do_electrons: true
do_met : true
do_small_R_jets: true
do_large_R_UFO_jets: true

Electron:
  ID: "MediumLH"
  Iso: "Loose_VarRad"
  amount: 0

Muon:
  ID: "Medium"
  Iso: "PflowLoose_VarRad"
  amount: 0

Lepton:
  amount: 0

# apply trigger lists to filter events
do_trigger_filtering: true

# write objects with overlap removal applied
# turning this on you have to decide on one large R jet collection
do_overlap_removal: true

#Enable cutflow 
save_vbshiggs_cutflow: true

# Toggles for reconstructed objects decorations
Small_R_jet:
  # btagging working points 
  btag_wp: "GN2v01_FixedCutBEff_90"
  amount: 2
  
  # to use multiple btagging WPs
  btag_extra_wps:
    - GN2v01_Continuous
    
# Include the TTree configuration and update details
ttree_output:
  include: EasyjetHub/AnalysisMiniTree-config.yaml
  # Our overrides. All defaults are off
  slim_variables_with_syst: true
  reco_outputs:
    small_R_jets: 'container_names.output.reco4PFlowJet'
    large_R_UFO_jets: 'container_names.output.reco10UFOJet'
    muons: 'container_names.output.muons'
    electrons: 'container_names.output.electrons'
    met : 'container_names.output.met'
  collection_options:
    small_R_jets:
      btag_info: true
