include: [vbshiggsAnalysis/RunConfig-common.yaml ]

# setting this to warning until the team decides they want to be using
# expert mode
expert_mode_warning_level: default

# Which analysis to consider
channels: ["SemiLep"]

## Run resolved category
do_resolved: true

# Use VBFRNN tagger
UseVBFRNN : false

# Toggles for object types
do_muons: true
do_electrons: true
do_met : true


Electron:
  ID: "LooseBLayerLH"
  Iso: "Loose_VarRad"
  amount: 2
  extra_wps:
    - ["LooseBLayerLH", "Tight_VarRad"]

    - ["MediumLH", "Loose_VarRad"]
    - ["MediumLH", "Tight_VarRad"]
    - ["MediumLH", "NonIso"]

    - ["TightLH", "Loose_VarRad"]
    - ["TightLH", "Tight_VarRad"]
    - ["TightLH", "NonIso"]

    - ["LooseDNNElectron", "Loose_VarRad"]
    - ["LooseDNNElectron", "Tight_VarRad"]

    - ["MediumDNNElectron", "Loose_VarRad"]
    - ["MediumDNNElectron", "Tight_VarRad"]

    - ["TightDNNElectron", "Loose_VarRad"]
    - ["TightDNNElectron", "Tight_VarRad"]
  do_IFF_decoration: true
  do_reco_decoration: true

Muon:
  ID: "Loose"
  Iso: "PflowLoose_VarRad"
  amount: 2
  extra_wps:
    - ["Loose", "PflowTight_VarRad"]
    
    - ["Medium", "PflowLoose_VarRad"]
    - ["Medium", "PflowTight_VarRad"]
    - ["Medium", "NonIso"]

    - ["Tight", "PflowLoose_VarRad"]
    - ["Tight", "PflowTight_VarRad"]
    - ["Tight", "NonIso"]

  do_IFF_decoration: true
  do_reco_decoration: true


# Toggles for reconstructed objects decorations
Small_R_jet:
  # btagging working points 
  btag_wp: "GN2v01_FixedCutBEff_90"
  amount: 0
  useFJvt: true
  # to use multiple btagging WPs
  btag_extra_wps:
    - GN2v01_Continuous

Large_R_jet:
  maxEta: 2.0
  amount: 1
  GN2X_hbb_wps:
    - "FlatMassQCDEff_0p25"
    - "FlatMassQCDEff_0p3"
    - "FlatMassQCDEff_0p37"
    - "FlatMassQCDEff_0p46"
    - "FlatMassQCDEff_0p58"
    - "FlatMassQCDEff_0p74"
    - "FlatMassQCDEff_0p94"
    - "FlatMassQCDEff_1p25"
    - "FlatMassQCDEff_1p55"
  wtag_type: "ANN" # ANN, DNN
  wtag_wp: "50"
  wtag_extra_wps: ["50","60","80","90"]


Lepton:
  amount: 1
  variables_int: ["isPrompt","truthOrigin", "truthType", "ele_ECIDS"]

OverlapRemoval:
  # Enable overlap removal between large-R jets and objects for which 
  # large-R jet OR removal is implemented in Athena
  do_large_R_jets: true
  do_small_R_jet_large_R_jet: false

# list of triggers per year to consider
Trigger:
  include: [vbshiggsAnalysis/trigger-lep.yaml]

CutList :
      - PASS_TRIGGER 
