include: vbshiggsAnalysis/RunConfig-common.yaml 

# Which analysis to consider
Channel: "FullLep"

# Toggles for object types
do_muons: true
do_electrons: true
do_met : true


Electron:
  ID: "TightLH"
  Iso: "NonIso"
  amount: 2
  extra_wps:
    - ["MediumLH", "Loose_VarRad"]
    - ["MediumLH", "Tight_VarRad"]
    - ["MediumLH", "TightTrackOnly_VarRad"]
    - ["MediumLH", "TightTrackOnly_FixedRad"]

    - ["TightLH", "Loose_VarRad"]
    - ["TightLH", "Tight_VarRad"]
    - ["TightLH", "TightTrackOnly_VarRad"]
    - ["TightLH", "TightTrackOnly_FixedRad"]
Muon:
  ID: "Tight"
  Iso: "NonIso"
  amount: 2
  extra_wps:
    - ["Medium", "PflowLoose_VarRad"]
    - ["Medium", "PflowTight_VarRad"]

    - ["Tight", "PflowLoose_VarRad"]
    - ["Tight", "PflowTight_VarRad"]


Lepton:
  amount: 2
  variables_int: ["isPrompt","truthOrigin", "truthType", "ele_ECIDS"]

# list of triggers per year to consider
trigger:
  include: vbshiggsAnalysis/trigger-lep.yaml

CutList :
      - AT_LEAST_TWO_LEPTONS
      - EXACTLY_TWO_LEPTONS
      - PASS_TRIGGER 
      - TWO_SS_CHARGE_LEPTONS
      - TWO_OS_CHARGE_LEPTONS
      - PASS_MET
      - AT_LEAST_ONE_B_JET
      - EXACTLY_TWO_B_JETS
      - PASS_DELTA_R_BB
      - PASS_mBB
      - PASS_VBS_BASELINE

Categories :
      - IS_SF
      - IS_ee
      - IS_mm
      - IS_em
      - Pass_ll
