include: [EasyjetHub/base-config.yaml]

do_CP_systematics: false

# Variables that we would want for nominal only nTuples
save_high_level_variables: true

### tagging jets vs RNN strategy
### false: select tagging jets ---> higgs candidate jets
### true : select higgs candidate jets ---> load VBF-RNN
UseVBFRNN : false

# Add truth VBS quark info
AddTruthVBSQuarks : false

# expand list to store nWLep truth information
Truth:
  DSID_nWLep_samples:
    - 525362 # MGPy8EG_ssWWhjj_llvvbbjj_EW8_LO_klp1
    - 525363 # MGPy8EG_ssWWhjj_llvvbbjj_EW8_LO_klp2
    - 525364 # MGPy8EG_ssWWhjj_llvvbbjj_EW8_LO_klp5
    - 525365 # MGPy8EG_ssWWhjj_llvvbbjj_EW8_LO_klp10
    - 525366 # MGPy8EG_ssWWhjj_llvvbbjj_EW8_LO_klm5
    - 525367 # MGPy8EG_ssWWhjj_ltvvbbjj_EW8_LO_klp1
    - 525368 # MGPy8EG_ssWWhjj_ltvvbbjj_EW8_LO_klp2
    - 525369 # MGPy8EG_ssWWhjj_ltvvbbjj_EW8_LO_klp5
    - 525370 # MGPy8EG_ssWWhjj_ltvvbbjj_EW8_LO_klp10
    - 525371 # MGPy8EG_ssWWhjj_ltvvbbjj_EW8_LO_klm5
    - 545778 # MGPy8EG_ssWWhjj_llvvbbjj_EW8_LO_k2vm7
    - 545779 # MGPy8EG_ssWWhjj_llvvbbjj_EW8_LO_k2vm4
    - 545780 # MGPy8EG_ssWWhjj_llvvbbjj_EW8_LO_k2vm2
    - 545781 # MGPy8EG_ssWWhjj_llvvbbjj_EW8_LO_k2v0
    - 545782 # MGPy8EG_ssWWhjj_llvvbbjj_EW8_LO_k2vp2
    - 545783 # MGPy8EG_ssWWhjj_llvvbbjj_EW8_LO_k2vp4
    - 545784 # MGPy8EG_ssWWhjj_llvvbbjj_EW8_LO_k2vp6
    - 545785 # MGPy8EG_ssWWhjj_llvvbbjj_EW8_LO_k2vp8

  DSID_vgammaOR:
    - 410470 # PhPy8EG_A14_ttbar_hdamp258p75_nonallhad
    - 410472 # PhPy8EG_A14_ttbar_hdamp258p75_dil

# Toggles for object types
do_muons: true
do_electrons: true
do_met : true
do_small_R_jets: true
do_large_R_UFO_jets: true

Electron:
  ID: "MediumLH"
  Iso: "Loose_VarRad"
  amount: 0
  ## Only correlation scheme supported
  correlationModelId: "TOTAL"

Muon:
  ID: "Medium"
  Iso: "PflowLoose_VarRad"
  amount: 0

Lepton:
  amount: 0

# apply trigger lists to filter events
do_trigger_filtering: true
# compute and store trigger scale factors
do_trigsf: true

do_overlap_removal: true
OverlapRemoval:
  # Enable overlap removal between large-R jets and objects for which 
  # large-R jet OR removal is implemented in Athena
  do_large_R_jets: true
  do_small_R_jet_large_R_jet: false

#Enable cutflow 
save_cutflow: true

# Include the TTree configuration and update details
ttree_output:
  include: [EasyjetHub/AnalysisMiniTree-config.yaml]
  # Our overrides. All defaults are off
  slim_variables_with_syst: true
  reco_outputs:
    small_R_jets: 'container_names.output.reco4PFlowJet'
    large_R_UFO_jets: 'container_names.output.reco10UFOJet'
    muons: 'container_names.output.muons'
    electrons: 'container_names.output.electrons'
    met : 'container_names.output.met'
  collection_options:
    small_R_jets:
      btag_info: true
    large_R_jets:
      truth_labels: true
