include: EasyjetHub/base-config.yaml

# Which analysis and channels to consider
do_lltt_analysis: true
channels: ["LepLep", "LepHad", "HadHad"]

# Toggles to bypass event selection for signal events 
bypass: false
# do AntiTau selection if needed
doAntiTau: false
# do AntiTau selection if needed
do_trigsf: false

# Toggles for object types
do_small_R_jets: true
do_large_R_UFO_jets: false
do_muons: true
do_electrons: true
do_taus: true
do_met : true
do_mmc : false
do_baseline : true

# Decay mode considered for truth decoration
Truth:
  decayModes: ["mmtt", "eett", "tttt"]

# small R config
Small_R_jet:
  # btagging nominal working point
  #btag_wp: "GN2v01_FixedCutBEff_77"
  btag_wp: "GN2v01_FixedCutBEff_77"
  btag_extra_wps:
    - GN2v01_Continuous

Electron:
  forceFullSimConfig: true
  ID: "LooseBLayerLH"
  Iso: "NonIso"
  #Iso: "Loose_VarRad"
  extra_wps:
    - ["TightLH", "NonIso"]
    #- ["TightLH", "Loose_VarRad"]

Muon:
  ID: "Loose"
  Iso: "NonIso"    
  #Iso: "PflowLoose_VarRad"
  extra_wps:
    - ["Medium", "NonIso"]
    #- ["Medium", "PflowLoose_VarRad"]

Tau:
  ID: "RNNLoose_eleid"
  extra_wps: ["RNNMedium_eleid"]
  addMuonRM: true
  amount: 2
  variables: ["RNN"]
  variables_int: ["pdgid", "truthOrig", "truthType", "EleRNN_WP"]

Lepton:
  amount: 2
  variables_int: ["truthOrig", "truthType"]

# list of triggers per year to consider
Trigger:
  include: llttAnalysis/trigger.yaml
# apply trigger lists to filter events
do_trigger_filtering: true
# use trigger selections in offline algorithms
do_trigger_offline_filtering: true

# write objects with overlap removal applied
# turning this on you have to decide on one large R jet collection
do_overlap_removal: false

#store_high_level_variables: true

# Include the TTree configuration and update details
ttree_output:
  include: EasyjetHub/AnalysisMiniTree-config.yaml
  # Our overrides. All defaults are off
  slim_variables_with_syst: true
  reco_outputs:
    met : 'container_names.output.met'
