include: [EasyjetHub/base-config.yaml]

do_CP_systematics: false

# tagging jets pairing options
# HighestMjjForwardJets or HighestMjjJets or LeadingPTjj 
TagJetsCriteria: "LeadingPTjj"
DeltaRJj: 1.0

# retrieve DisCoJet tagger (yes only on LLJ1)
loadDisCoJet: True
DisCoJetCfg: "SmoothedContainedVTagger_AntiKt10VanillaSD_HP_1VarDisCoJet_v3p4.dat"
# HighestPT or HighestScore order
SigJetsCriteria: "HighestPT"
# use GN2x information or not (not on current LLJ1 ptag)
loadGN2x: False

# Toggles for object types
do_muons: true
do_electrons: false
do_met : false
do_small_R_jets: true
do_large_R_UFO_jets: true
do_VR_jets: false

Muon:
  ID: "Medium"
  Iso: "PflowLoose_VarRad"
  amount: 0

# apply trigger lists to filter events
do_trigger_filtering: false

# write objects with overlap removal applied
# turning this on you have to decide on one large R jet collection
do_overlap_removal: true
OverlapRemoval:
  # Enable overlap removal between large-R jets and objects for which 
  # large-R jet OR removal is implemented in Athena
  do_large_R_jets: true
  do_small_R_jet_large_R_jet: false

#Enable cutflow 
save_cutflow: true

# Toggles for reconstructed objects decorations
Small_R_jet:
  # btagging working points 
  btag_wp: "GN2v01_FixedCutBEff_90"
  amount: 2
  
  # to use multiple btagging WPs
  btag_extra_wps:
    - GN2v01_Continuous
    
# Include the TTree configuration and update details
ttree_output:
  include: [EasyjetHub/AnalysisMiniTree-config.yaml]
  # Our overrides. All defaults are off
  slim_variables_with_syst: true
  reco_outputs:
    small_R_jets: 'container_names.output.reco4PFlowJet'
    large_R_UFO_jets: 'container_names.output.reco10UFOJet'
  collection_options:
    small_R_jets:
      btag_info: true
