include: [bbttAnalysis/RunConfig-bbtt-base.yaml]

channels: ["HadHad","LepHad","ZCR","TopEMuCR"]

Trigger:
  selection:
    include: [bbttAnalysis/trigger_full.yaml]

# Produce separate files per channel + CutBookKeeper
splitOutputTree: true
splitCBK: true
