include: [EasyjetHub/base-config.yaml]

# Which analysis to consider
do_jjjj: true

# Toggles for object types
do_small_R_jets: True

# Which analysis to consider
channels: ["jjjj"]

CutList :
  - PASS_TRIGGER 
# Toggles for reconstructed objects decorations
Small_R_jet:
  btag_wp: ""
  runBJetPtCalib: False
  amount: 4
#do_CP_systematics: true
systematics_regex: [".*"]
# list of triggers per year to consider
Trigger:
  include: [jjjjAnalysis/trigger.yaml]

do_trigger_filtering: true

save_cutflow: false


# Include the TTree configuration and update details
ttree_output:
  include: [EasyjetHub/AnalysisMiniTree-config.yaml]
  slim_variables_with_syst: true
  # Our overrides. All defaults are off
  reco_outputs:
    small_R_jets: 'container_names.output.reco4PFlowJet'
  truth_outputs:
    small_R_jets: 'container_names.input.truth4Jet'
