include: bbllAnalysis/RunConfig-bbll-bypass.yaml

Electron:
  forceFullSimConfig: true

NeutrinoWeighting:
  include: NeutrinoWeighting.yaml

do_resonant_PNN: true

mX_values: [251, 260, 300, 400, 500, 600, 800, 1000]