include: bbttAnalysis/RunConfig-bbtt-base.yaml

channels: ["HadHad"]

Trigger:
  selection:
    include: bbttAnalysis/trigger_taus.yaml

# Produce separate files per channel + CutBookKeeper
splitOutputTree: true
splitCBK: true