include: bbttAnalysis/RunConfig-bbtt-base.yaml

# Toggles for object types
do_large_R_UFO_jets: true

# overlap removal
OverlapRemoval:
  do_small_R_jet_large_R_jet: false
  do_photon_jet: false

Large_R_jet:
  # correction for the b-jet correction
  # adding back muon pt inside the large-R jet. 
  runMuonJetPtCorr: true
  # TODO: __BOOSTED__ which working point do we need ??
  # b-tag efficiency working points, do we have to select just one ?
  GN2X_hbb_wps:
    - "FlatMassQCDEff_0p25"
    - "FlatMassQCDEff_0p3"
    - "FlatMassQCDEff_0p37"
    - "FlatMassQCDEff_0p46"
    - "FlatMassQCDEff_0p58"
    - "FlatMassQCDEff_0p74"
    - "FlatMassQCDEff_0p94"
    - "FlatMassQCDEff_1p25"
    - "FlatMassQCDEff_1p55"
  amount_leadingjet: 2