include: [bbttAnalysis/RunConfig-bbtt-base-largeR-jets.yaml]

# Which analysis and channels to consider
# TODO: __BOOSTED__ boosted analysis is only HadHad
channels: ["Boosted", "HadHad"]

# TODO: __BOOSTED__ this is a temporary flag, as we don't want to
# interfere with the resolved analysis.
do_boosted_dihiggs: true

# split output file
splitCBK: true
splitOutputTree: true

# Triggers
Trigger:
  selection:
    include: [trigger_boosted.yaml]
  # TODO: __BOOSTED__ for the moment no SF are avalailable
  scale_factor:
    doSF: false

# Update output configs for large-R jets
ttree_output:
  include: [EasyjetHub/AnalysisMiniTree-config.yaml]
  slim_variables_with_syst: true
  reco_outputs:
    large_R_UFO_jets: 'container_names.output.reco10UFOJet'
    small_R_jets: 'container_names.output.reco4PFlowJet'
    taus: 'container_names.output.taus'
    ditaus: 'container_names.output.ditaus'
  collection_options:
    large_R_jets:
      substructure_info: true
      truth_labels: true
      btag_info: true
      truth_parent_info: true
      run_selection: true
    small_R_jets:
      btag_info: true
      ruth_parent_info: true
      no_bjet_calib_p4: true
      run_selection: true
  truth_outputs:
    large_R_jets: 'container_names.input.truth10SoftDropJet'
    small_R_jets: 'container_names.input.truth4Jet'
    higgs_particle: 'container_names.output.truthHHParticles'
    taus: 'container_names.input.truthtaus'

# Enable cutflow 
CutList:
  - AT_LEAST_TWO_LRJETS
  - pass_Boosted
  - pass_HadHad


Small_R_jet:
  amount_bjet: 0

Tau:
  amount: 0

Lepton:
  amount: 0
