include: bbttAnalysis/RunConfig-bbtt-base.yaml

channels: ["HadHad_2B","HadHad_1B","LepHad_2B","LepHad_1B","ZCR","TopEMuCR"]

bypass: true
do_trigger_filtering: false

do_large_R_UFO_jets: true
OverlapRemoval:
  do_large_R_jets: false
  do_small_R_jet_large_R_jet: false

Large_R_jet:
  runMuonJetPtCorr: true

# Update output configs for large-R jets
ttree_output:
  reco_outputs:
    large_R_UFO_jets: 'container_names.output.reco10UFOJet'
  collection_options:
    large_R_jets:
      substructure_info: true
      truth_labels: true
  truth_outputs:
    higgs_particle: 'container_names.output.truthHHParticles'
