#!/usr/bin/env bash

set -Eeu


################################################
# mode-based switches
################################################

# standard samples
DATA_2018=data18_13TeV.00362204.physics_Main.DAOD_PHYS_10evts.r13286_p4910_p5511.pool.root
DATA_2022=data22_13p6TeV.00436656.physics_Main.DAOD_PHYS_10evts.r14190_p5449_p5511.pool.root
PHYS_JETS=mc20_13TeV.364704.Pythia8EvtGen_A14NNPDF23LO_jetjet_JZ4WithSW.DAOD_PHYS_10evts.e7142_s3681_r13145_p5511.pool.root
PHYS_TTBAR_MC20=mc20_13TeV.410471.PhPy8EG_A14_ttbar_hdamp258p75_allhad.DAOD_PHYS_10evts.e6337_s3681_r13145_p5511.pool.root
PHYS_SH4B_BOOSTED=mc20_13TeV.801636.Py8EG_A14NNPDF23LO_XHS_X3000_S70_4b.DAOD_PHYS_10evts.e8448_a899_r13145_p5511.pool.root
PHYSLITE_SH4B_VERY_BOOSTED=mc20_13TeV.801636.Py8EG_A14NNPDF23LO_XHS_X3000_S70_4b.DAOD_PHYSLITE_10evts.e8448_a899_r13145_p5511.pool.root
PHYS_HH4B_MC21=mc21_13p6TeV.601479.PhPy8EG_HH4b_cHHH01d0.DAOD_PHYS_10evts.e8472_s3873_r13829_p5511.pool.root
PHYSLITE_HH4B_MC21=mc21_13p6TeV.601479.PhPy8EG_HH4b_cHHH01d0.DAOD_PHYSLITE_10evts.e8472_s3873_r13829_p5511.pool.root
PHYS_TTBAR_MC21=mc21_13p6TeV.601237.PhPy8EG_A14_ttbar_hdamp258p75_allhad.DAOD_PHYS_10evts.e8453_s3873_r13829_p5511.pool.root
PHYS_JETS_MC21=mc21_13p6TeV.801170.Py8EG_A14NNPDF23LO_jj_JZ5.DAOD_PHYS_10evts.e8453_s3873_r13829_p5511.pool.root

declare -A DATAFILES=(
    [data18-fast]=${DATA_2018}
    [data18]=${DATA_2018}
    [data22-fast]=${DATA_2022}
    [data22]=${DATA_2022}
    [jets-mc20-fast]=${PHYS_JETS}
    [jets-mc20]=${PHYS_JETS}
    [ttbar-mc20-fast]=${PHYS_TTBAR_MC20}
    [ttbar-mc20]=${PHYS_TTBAR_MC20}
    [hh4b-mc21]=${PHYS_HH4B_MC21}
    [hh4b-mc21-syst]=${PHYS_HH4B_MC21}
    [sh4b-boosted-mc20-fast]=${PHYS_SH4B_BOOSTED}
    [sh4b-boosted-mc20]=${PHYS_SH4B_BOOSTED}
    [ttbar-mc21-fast]=${PHYS_TTBAR_MC21}
    [ttbar-mc21]=${PHYS_TTBAR_MC21}
    [ttbar-mc21-syst]=${PHYS_TTBAR_MC21}
    [physlite-sh4b-very-boosted-mc20-fast]=${PHYSLITE_SH4B_VERY_BOOSTED}
    [physlite-sh4b-very-boosted-mc20]=${PHYSLITE_SH4B_VERY_BOOSTED}
    [physlite-hh4b-mc21-fast]=${PHYSLITE_HH4B_MC21}
    [physlite-hh4b-mc21]=${PHYSLITE_HH4B_MC21}
)

declare -A TESTS=(
    [data18-fast]=data-ntuple-dump-fast
    [data22-fast]=data-ntuple-dump-fast
    [jets-mc20-fast]=ntuple-dump-fast
    [jets-mc20]=ntuple-dump
    [ttbar-mc20-fast]=ntuple-dump-fast
    [ttbar-mc20]=ntuple-dump
    [sh4b-boosted-mc20-fast]=ntuple-dump-fast
    [sh4b-boosted-mc20]=ntuple-dump
    [hh4b-mc21]=ntuple-dump
    [hh4b-mc21-syst]=ntuple-dump-syst
    [ttbar-mc21-fast]=ntuple-dump-fast
    [ttbar-mc21]=ntuple-dump
    [ttbar-mc21-syst]=ntuple-dump-syst
    [physlite-sh4b-very-boosted-mc20-fast]=ntuple-dump-physlite-fast
    [physlite-sh4b-very-boosted-mc20]=ntuple-dump-physlite
    [physlite-hh4b-mc21-fast]=ntuple-dump-physlite-fast
    [physlite-hh4b-mc21]=ntuple-dump-physlite
)

# some common variables in the tests
CONFIG=${HH4bAnalysis_DIR}/data/HH4bAnalysis/RunConfig.yaml
COMMON=" --allow-no-ptag --runConfig $CONFIG"

# specific tests
ntuple-dump() {
    VariableDumperConfig.py $COMMON --filesInput $1
    metadata-check -v
}
ntuple-dump-syst() {
    VariableDumperConfig.py $COMMON --filesInput $1 --do-CP-systematics True
    metadata-check -v
}
ntuple-dump-fast() {
    local OPTS="$COMMON --cache-metadata --filesInput $1"
    local CMD="VariableDumperConfig.py $OPTS"
    $CMD --config-only True
    echo "rerunning $CMD to time"
    $CMD --timeout 30 --h5-output test.h5
    metadata-check -v
}
data-ntuple-dump-fast() {
    local OPTS="$COMMON --cache-metadata --filesInput $1"
    OPTS+=" --disable-trigger-filtering"
    local CMD="VariableDumperConfig.py $OPTS"
    $CMD --config-only True
    echo "rerunning $CMD to time"
    $CMD --timeout 30 --h5-output test.h5
    metadata-check -v
}
ntuple-dump-physlite() {
    VariableDumperConfig.py $COMMON --disable-calib --filesInput $1
    metadata-check -v
}
ntuple-dump-physlite-fast() {
    local OPTS="$COMMON --cache-metadata --filesInput $1 --disable-calib"
    local CMD="VariableDumperConfig.py $OPTS"
    $CMD --config-only True
    echo "rerunning $CMD to time"
    $CMD --timeout 30
    metadata-check -v
}

################################################
# parse arguments
################################################

ALL_MODES=${!TESTS[*]}

print-usage() {
    echo "usage: ${0##*/} [-hv] [-d <dir>] (${ALL_MODES[*]// /|})" 1>&2
}

usage() {
    print-usage
    exit 1;
}

help() {
    print-usage
    cat <<EOF

The ${0##*/} utility will download a test DAOD file and run it.

Options:
 -d <dir>: specify directory to run in
 -v: verbose output (INFO level in Athena)
 -h: print help

If no -d argument is given we'll create one in /tmp and work there.

EOF
    exit 1
}

DIRECTORY=""
DATA_URL=https://gitlab.cern.ch/easyjet/hh4b-test-files/-/raw/master/
LOG_LEVEL="WARNING"

while getopts ":d:hv" o; do
    case "${o}" in
        d) DIRECTORY=${OPTARG} ;;
        h) help ;;
        v) LOG_LEVEL="INFO" ;;
        *) usage ;;
    esac
done
shift $((OPTIND-1))

if (( $# != 1 )) ; then
    usage
fi

MODE=$1

# add common options
COMMON+=" -l ${FORCED_LOG_LEVEL-${LOG_LEVEL}}"

############################################
# Check that all the modes / paths exist
############################################
#
if [[ ! ${DATAFILES[$MODE]+x} ]]; then usage; fi
DOWNLOAD_PATH=${DATAFILES[$MODE]}
FILE=${DOWNLOAD_PATH##*/}

if [[ ! ${TESTS[$MODE]+x} ]]; then usage; fi
RUN=${TESTS[$MODE]}


#############################################
# now start doing stuff
#############################################
#
if [[ -z ${DIRECTORY} ]] ; then
    DIRECTORY=$(mktemp -d)
    echo "running in ${DIRECTORY}" >&2
fi

if [[ ! -d ${DIRECTORY} ]]; then
    if [[ -e ${DIRECTORY} ]] ; then
        echo "${DIRECTORY} is not a directory" >&2
        exit 1
    fi
    mkdir ${DIRECTORY}
fi
cd $DIRECTORY

# get files
if [[ ! -f ${FILE} ]] ; then
    echo "getting file ${FILE}" >&2
    curl -s ${DATA_URL}/${DOWNLOAD_PATH} > ${FILE}
fi

# now run the test
echo "running ${RUN}"
$RUN $FILE

