include: EasyjetHub/base-config.yaml
# Toggles for object types
do_small_R_jets: true
do_large_R_Topo_jets: true
do_large_R_UFO_jets: true
do_VR_jets: true
do_muons: true
# btagging working points for small Rjets
btag_wps:
    - DL1dv01_FixedCutBEff_70
    - DL1dv01_FixedCutBEff_77
    - DL1dv01_FixedCutBEff_85
    - GN120220509_FixedCutBEff_70
    - GN120220509_FixedCutBEff_77
    - GN120220509_FixedCutBEff_85

# btagging working points for Variable Radius Track jets
vr_btag_wps:
    - DL1r_FixedCutBEff_77
    - DL1r_FixedCutBEff_85

# "Auto" configures triggers for "HH4bResolved", "HH4bBoosted"
# We can also be explicit here I think
trigger_list: ["HH4bResolved", "HH4bBoosted"]
# apply loose jet cleaning only
loose_jet_cleaning: true
# which objects to write
write_small_R_jets: true
write_large_R_Topo_jets: true
write_large_R_UFO_jets: true
write_VR_jets: true
# additional small R info
write_small_R_higgs_parent_info: true
write_small_R_btag: true
write_small_R_JVT_details: true
write_small_R_no_bjet_calib: true
write_small_R_gn2_branches: true
# additional Large R info
write_large_R_truth_labels: true
# turned off automatically if MC
write_truth_small_R_jets: true
write_truth_large_R_jets: true
write_truth_higgs: true
