# Toggles for object types
do_small_R_jets: true
do_large_R_Topo_jets: false
do_large_R_UFO_jets: true
do_VR_jets: true
do_muons: true
do_electrons: false
do_photons: false
# btagging working points for small Rjets
btag_wps:
    - DL1dv01_FixedCutBEff_70
    - DL1dv01_FixedCutBEff_77
    - DL1dv01_FixedCutBEff_85
    - GN120220509_FixedCutBEff_70
    - GN120220509_FixedCutBEff_77
    - GN120220509_FixedCutBEff_85

# btagging working points for Variable Radius Track jets
vr_btag_wps:
    - DL1r_FixedCutBEff_77
    - DL1r_FixedCutBEff_85

# list of triggers to apply
# "Auto" configures mc from the r-tag, data from year, e.g. data22
trigger_year: Auto
# "Auto" configures triggers for "HH4bResolved", "HH4bBoosted"
# We can also be explicit here I think
trigger_list: ["HH4bResolved", "HH4bBoosted"]
# apply trigger lists to filter events
do_trigger_filtering: false
# disable CP Algs for calibration
disable_calib: false
# apply loose jet cleaning only
loose_jet_cleaning: true
# if you want to run a baseline diHiggs analyses
do_resolved_dihiggs_analysis: false
do_boosted_dihiggs_analysis: false
# if you want to truth match (is MC protected)
truth_match_resolved: false
truth_match_boosted: false
# Whether to activate CP alg systematic variations
do_CP_systematics: false
systematics_regex: [".*"]
# write objects with overlap removal applied
# turning this on you have to decide on one large R jet collection
do_overlap_removal: false
# which objects to write
write_small_R_jets: true
write_large_R_Topo_jets: false
write_large_R_UFO_jets: true
write_VR_jets: true
write_muons: false
write_electrons: false
write_photons: false
# additional small R info 
write_small_R_higgs_parent_info: true
write_small_R_btag: true
write_small_R_JVT_details: true
write_small_R_no_bjet_calib: true
write_small_R_gn2_branches: true
# additional Large R info
write_large_R_substructure: false
# turned off automatically if MC
write_truth_small_R_jets: true
write_truth_large_R_jets: true
write_truth_higgs: true
# whether to output a meta data file
meta_cache: false
