# btagging working points for small Rjets
btag_wps:
    - DL1dv00_FixedCutBEff_70
    - DL1dv00_FixedCutBEff_77
    - DL1dv00_FixedCutBEff_85
    - GN120220509_FixedCutBEff_70
    - GN120220509_FixedCutBEff_77
    - GN120220509_FixedCutBEff_85
# btagging working points for Variable Radius Track jets
vr_btag_wps:
    - DL1r_FixedCutBEff_77
    - DL1r_FixedCutBEff_85

# list of triggers to apply
# "Auto" configures mc from the r-tag, data from year, e.g. data22
trigger_year: Auto
# "Auto" configures triggers for "HH4bResolved", "HH4bBoosted"
# We can also be explicit here I think
trigger_list: ["HH4bResolved", "HH4bBoosted"]
# apply loose jet cleaning only
loose_jet_cleaning: true
# if you want to run a baseline diHiggs analyses
do_resolved_dihiggs_analysis: false
do_boosted_dihiggs_analysis: false
# if you want to truth match (is MC protected)
truth_match_resolved: false
truth_match_boosted: false
# Whether to activate CP alg systematic variations
do_CP_systematics: false
