include: [EasyjetHub/base-config.yaml]

# setting this to warning until the team decides they want to be using
# expert mode
expert_mode_warning_level: default

# Which analysis to consider
do_ttCalib: false
do_ZbbyCalib: false
do_ZbbjCalib: false
do_ZlljCalib: false
do_ZllyCalib: true
# We would use Alg in src/ZllCalibSelectionAlg

# Toggles to bypass event selection
bypass: false
# VgammaORTool Setup
do_VgammaOR: false
bypass_VGammaOR: true
VGammaOR_ypT_cuts: [20.e+3] #photon
VGammaOR_dR_lepton_photon_cuts: [0.1]

# Toggles for object types
do_large_R_UFO_jets: true
do_small_R_jets: true
do_muons: true
do_electrons: true
do_photons: true

# Toggles for reconstructed objects decorations
Small_R_jet:
  btag_wp: "GN2v01_FixedCutBEff_77"
  maxEta: 2.5
  selectBjet: false

Large_R_jet:
  min_pT: 200.e+3
  maxEta: 2.0
  runMuonJetPtCorr: false
  GN2X_hbb_wps:
    - "FlatMassQCDEff_0p25"
    - "FlatMassQCDEff_0p3"
    - "FlatMassQCDEff_0p37"
    - "FlatMassQCDEff_0p46"
    - "FlatMassQCDEff_0p58"
    - "FlatMassQCDEff_0p74"
    - "FlatMassQCDEff_0p94"
    - "FlatMassQCDEff_1p25"
    - "FlatMassQCDEff_1p55"

Photon:
  ID: "Tight" # Loose, Tight
  Iso: "FixedCutTight"
  min_pT: 150.e+3

Electron:
  min_pT: 7.e+3
  ID: "MediumLH"
  Iso: "TightTrackOnly_VarRad"
  extra_wps:
    - ["LooseBLayerLH", "NonIso"]

Muon:
  min_pT: 7.e+3
  ID: "HighPt"
  maxEta: 2.7
  Iso: "Tight_VarRad"
  extra_wps:
    - ["Loose", "PflowLoose_VarRad"]

# list of triggers per year to consider
Trigger:
  include: [XbbCalib/trigger_Zlly.yaml]
# apply trigger lists to filter events
do_trigger_filtering: true

# write objects with overlap removal applied
# turning this on you have to decide on one large R jet collection
do_overlap_removal: true

OverlapRemoval:
  # Enable overlap removal between large-R jets and objects for which
  # large-R jet OR removal is implemented in Athena
  do_large_R_jets: true
  # Enable overlap removal between small-R jets and large-R jets
  # Athena default is true
  do_small_R_jet_large_R_jet: false

# Include the TTree configuration and update details
ttree_output:
  include: [EasyjetHub/AnalysisMiniTree-config.yaml]
  # Our overrides. All defaults are off
  reco_outputs:
    large_R_UFO_jets: 'container_names.output.reco10UFOJet'
    muons: 'container_names.output.muons'
    electrons: 'container_names.output.electrons'
    small_R_jets: 'container_names.output.reco4PFlowJet'
    photons : 'container_names.output.photons'
  # truth_outputs:
  #   # small_R_jets: 'container_names.output.truth4Jet'
  #   large_R_jets: 'container_names.output.truth10SoftDropJet'
  collection_options:
    large_R_jets:
      run_selection: true
    small_R_jets:
      btag_info: true
      run_selection: true
    electrons:
      run_selection: true
    muons:
      run_selection: true
    photons:
      run_selection: true
