include: [XbbCalib/RunConfig_Zlly.yaml]


# Run all CP syst
do_CP_systematics: true
systematics_regex: [".*(MUON|MET|JER).*"] 

# Do not output any trees 
ttree_output:
  include: [EasyjetHub/AnalysisMiniTree-config.yaml]
