include: EasyjetHub/base-config.yaml

# Which analysis to consider
do_XbbCalib: true

# Toggles to bypass event selection
bypass: false

# Toggles for object types
do_large_R_UFO_jets: true
do_small_R_jets: true
do_muons: true
do_electrons: true
do_met: true

# Toggles for reconstructed objects decorations
Small_R_jet:
  min_pT: 28.e+3
  btag_wp: "GN2v01_FixedCutBEff_77"

Large_R_jet:
  min_pT: 200.e+3

Electron:
  min_pT: 28.e+3
  ID: "TightLH"
  Iso: "Tight_VarRad"

Muon:
  min_pT: 28.e+3
  ID: "Medium"
  Iso: "PflowTight_VarRad"

# Include the TTree configuration and update details
ttree_output:
  - AnalysisMiniTree:
    include: EasyjetHub/AnalysisMiniTree-config.yaml
    # Our overrides. All defaults are off
    reco_outputs:
      large_R_UFO_jets: 'container_names.output.reco10UFOJet'
      small_R_jets: 'container_names.output.reco4PFlowJet'
      muons: 'container_names.output.muons'
      electrons: 'container_names.output.electrons'
      met : 'container_names.output.met'
    collection_options:
      #large_R_jets:
      #  run_selection: true
      small_R_jets:
        btag_info: true
        run_selection: true
      electrons:
        run_selection: true
      muons:
        run_selection: true
