
include: [XbbCalib/RunConfig_Zllj.yaml]

# Run all CP syst
do_CP_systematics: true
systematics_regex: ["^(?!.*(JET)).*$"] 

# Do not output any trees, slim down systematics
ttree_output:
  include: [EasyjetHub/AnalysisMiniTree-config.yaml]
