include: [VBSVV4qAnalysis/RunConfig-common.yaml ]

# Which analysis to consider
channels: ["JJ"]

# Toggles for object types

# list of triggers per year to consider
Trigger:
  include: [VBSVV4qAnalysis/trigger-jet.yaml]

CutList :
  - PASS_TRIGGER 
  - PASS_ONE_LARGE_JET

UseVBFRNN : true
VerVBFRNN : VBFRNNv1p0p0

#Categories :
