include: EasyjetHub/base-config.yaml

channels: ["SR","WZCR","misIDCR", "incVR", "LowDyVR", "LowMjjVR", "LowNjVR", "tFakeVR", "pass_tEWKVR", "pass_lllVR", "ZeeVR"]

# Which analysis to consider
do_ssWW_analysis: true

bypass: false


# Toggles for object types
do_small_R_jets: true
do_muons: true
do_electrons: true
do_met : true

# Toggles for reconstructed objects decorations
Small_R_jet:
  min_pT: 20.e+3  # for the jets entering the MET computation and the overlap removal
  max_eta: 4.5
  min_pT_ssWW: 20.e+3 # for the jet selection
  max_eta_ssWW: 4.5
  # btagging working points 
  btag_wp: "GN2v01_FixedCutBEff_85"
  amount: 2
  amount_bjet: 0
  # to use multiple btagging WPs
  btag_extra_wps:
    - GN2v01_FixedCutBEff_77
    - GN2v01_FixedCutBEff_70
    
  variables_int_bjets: ["truthLabel"]

Electron:
  maxD0Significance: 5 
  maxDeltaZ0SinTheta: 0.5
  ID: "LooseBLayerLH"
  Iso: "NonIso"
  min_pT: 4.5e+3
  min_pT_ssWW: 4.5e+3
  do_IFF_decoration: true

Muon:
  maxD0Significance: 15
  maxDeltaZ0SinTheta: 1.5
  ID: "Loose"
  Iso: "NonIso"
  min_pT: 3.e+3
  max_eta: 2.5 # no recommendation yet for forward muons with eta between 2.5 and 2.7.
  min_pT_ssWW: 3.e+3
  max_eta_ssWW: 2.5 # no recommendation yet for forward muons with eta between 2.5 and 2.7.
  do_IFF_decoration: true

Lepton:
  amount: 3
  variables_int: ["isPrompt","truthOrigin", "truthType", "ele_ECIDS"]


# list of triggers per year to consider
Trigger:
  include: ssWWAnalysis/trigger.yaml
# apply trigger lists to filter events
do_trigger_filtering: true

# write objects with overlap removal applied
# turning this on you have to decide on one large R jet collection
do_overlap_removal: true
OverlapRemoval:
  # Enable overlap removal between large-R jets and objects for which 
  # large-R jet OR removal is implemented in Athena
  do_large_R_jets: false
  do_small_R_jet_large_R_jet: false

#Enable cutflow 
save_cutflow: true

CutList :
  - PASS_TRIGGER
  - PASS_TWO_LEPTONS
  - PASS_LEPTON_ID
  - EXACTLY_TWO_LEPTONS
  - TWO_SAME_CHARGE_LEPTONS
  - DILEPTON_MASS_THRESHOLD
  - DILEPTON_MASS_SIDEBAND_EE
  - AT_LEAST_TWO_JETS
  - DIJETS_MASS_LOW
  - MET
  - BJET_VETO
  - DIJETS_DELTA_RAPIDITY
  - DIJETS_MASS_HIGH

Categories :
  - IS_ee
  - IS_mm
  - IS_em
  - IS_me

# Include the TTree configuration and update details
ttree_output:
  include: EasyjetHub/AnalysisMiniTree-config.yaml
  # Our overrides. All defaults are off
  slim_variables_with_syst: true
  reco_outputs:
    small_R_jets: 'container_names.output.reco4PFlowJet'
    muons: 'container_names.output.muons'
    electrons: 'container_names.output.electrons'
    met : 'container_names.output.met'
  collection_options:
    small_R_jets:
      btag_info: true
      # JVT_details: true
