include: EasyjetHub/base-config.yaml

# Which analysis to consider
do_ssWW_analysis: true

bypass: false


# Toggles for object types
do_small_R_jets: true
do_muons: true
do_electrons: true
do_met : true

# Toggles for reconstructed objects decorations
small_R_jet:
  min_pT: 20000  # for the jets entering the MET computation and the overlap removal
  max_eta: 4.5
  min_pT_ssWW: 20000 # for the jet selection
  max_eta_ssWW: 4.5
  # btagging working points 
  btag_wp: "GN2v01_FixedCutBEff_85"
  amount: 2
  amount_bjet: 2
  # to use multiple btagging WPs
  btag_extra_wps:
    - GN2v01_FixedCutBEff_77
    - GN2v01_FixedCutBEff_70
    
  variables_int_bjets: ["truthLabel"]

Electron:
  trackSelection: true
  maxD0Significance: 5 
  maxDeltaZ0SinTheta: 0.5
  ID: "LooseLH"
  Iso: None
  min_pT: 4500
  max_eta: 2.47
  min_pT_ssWW: 4500 
  max_eta_ssWW: 2.47

Muon:
  trackSelection: true
  maxD0Significance: 15
  maxDeltaZ0SinTheta: 1.5
  ID: "Loose"
  Iso: None
  min_pT: 3000
  max_eta: 2.5 # no recommendation yet for forward muons with eta between 2.5 and 2.7.
  min_pT_ssWW: 3000
  max_eta_ssWW: 2.5 # no recommendation yet for forward muons with eta between 2.5 and 2.7.

Lepton:
  amount: 2
  variables_int: ["isPrompt","truthOrigin", "truthType"]


# list of triggers per year to consider
trigger:
  include: ssWWAnalysis/trigger.yaml

# apply trigger lists to filter events
do_trigger_filtering: true

# write objects with overlap removal applied
# turning this on you have to decide on one large R jet collection
do_overlap_removal: true

#Enable cutflow 
save_ssWW_cutflow: true

CutList :
      - PASS_TRIGGER
      - PASS_TWO_LEPTONS
      - EXACTLY_TWO_LEPTONS
      - TWO_SAME_CHARGE_LEPTONS
      - DILEPTON_MASS_THRESHOLD
      - DILEPTON_MASS_SIDEBAND_EE
      - MET
      - AT_LEAST_TWO_JETS
      - DIJETS_MASS
      - DIJETS_DELTA_RAPIDITY
      - BJET_VETO

Categories :
      - IS_ee
      - IS_mm
      - IS_em

# Include the TTree configuration and update details
ttree_output:
  - AnalysisMiniTree:
    include: EasyjetHub/AnalysisMiniTree-config.yaml
    # Our overrides. All defaults are off
    slim_variables_with_syst: true
    reco_outputs:
      small_R_jets: 'container_names.output.reco4PFlowJet'
      muons: 'container_names.output.muons'
      electrons: 'container_names.output.electrons'
      met : 'container_names.output.met'
    collection_options:
      small_R_jets:
        btag_info: true
        # JVT_details: true
    truth_outputs:
      small_R_jets: 'container_names.input.truth4Jet'
