include: [EasyjetHub/base-config.yaml]

do_Monojet_analysis: true
bypass: false

met_cut: 200

do_small_R_jets: true
do_large_R_Topo_jets: true
do_muons: true
do_electrons: true
do_taus: true
do_met: true

add_BadBatman_jet_cleaning: false
do_event_cleaning: true

Small_R_jet:
  min_pT: 20.e+3
  max_eta: 4.5
  max_eta_central: 2.5
  amount: 4
  btag_wp: "" 
  runBJetPtCalib: false
  btag_extra_wps:
    - GN2v01_Continuous
  monojet_btagWPs: ["90","77","65"]
  variables_int_allJets: ["pcbt","TIGHT"]
  do_parent_decoration: false


Large_R_jet:
  amount: 4
  min_pT: 25
  max_eta: 2.5
  min_m: 40
  max_m: 600
  variables_LargeRJets: ["pt", "eta", "phi", "E", "m","GN2Xv01_phbb","GN2Xv01_phcc", "GN2Xv01_pqcd", "GN2Xv01_ptop","ECF1", "ECF2", "ECF3", "Split12", "Split23", "Tau1_wta", "Tau2_wta", "Tau3_wta", "Qw"]
  do_parent_decoration: false


Electron:
  amount: 0
  crackVeto: true
  trackSelection: true
  ID: "LooseBLayerLH"
  Iso: "Loose_VarRad"
  min_pT: 7.e+3
  max_eta: 2.47

# amount doesn't work as cut, it just specifies more info for the selected amount of objects (e.g. jet1,jet2,jet3,..)

Muon:
  amount: 0
  trackSelection: true
  ID: "Loose"
  Iso: "Loose_VarRad"
  min_pT: 7.e+3
  max_eta: 2.5


Tau:
  amount: 0
  ID: "Loose"
  min_pT: 20.e+3
  max_eta: 2.5
  crackVeto: true


Trigger:
  include: [monojetAnalysis/trigger_MET.yaml]

do_trigger_filtering: false

do_overlap_removal: true
OverlapRemoval:
  # Enable overlap removal between large-R jets and objects for which 
  # large-R jet OR removal is implemented in Athena
  do_large_R_jets: false
  do_small_R_jet_large_R_jet: false

  
save_Monojet_cutflow: true

CutList:
  - LEPTON_VETO
  - LARGEJETCUT
  - PASS_TRIGGER
  - METCUT
  - TIGHT_LEADING_CUT
#  - JETCUT
  - ALL_CUTS

ttree_output:
  include: [EasyjetHub/AnalysisMiniTree-config.yaml]
  reco_outputs:
    met : 'container_names.output.met'

  slim_variables_with_syst: true
