include: [bbyyAnalysis/RunConfig-HH_H-base.yaml]

# flag that toggles run-through mode in the SelectorAlg
bypass: false

# name that will go in the tree bbyy_pass_<selection_name>_%SYS%
selection_name: "loosest"

CutList :
      - PASS_TRIGGER
      - PASS_TRIGGER_MATCHING
      - DIPHOTON_MASS
      
Truth:
  do_STXS: true
