include: [bbyyAnalysis/RunConfig-bbyy-bypass.yaml]

do_CP_systematics: true
systematics_regex: [".*"]

save_cutflow: false
save_extra_vars: false
do_GNN2bjetSelection: false
save_HbbCand_vars: false
save_pass_trigger_info: false
