include: bbyyAnalysis/RunConfig-bbyy.yaml

# flag that toggles run-through mode in the SelectorAlg
bypass: false

# name that will go in the tree bbyy_pass_<selection_name>_%SYS%
selection_name: "loose"

CutList :
      - PASS_TRIGGER
      - TWO_TIGHTID_ISO_PHOTONS
      - DIPHOTON_MASS
      - AT_LEAST_TWO_JETS
