include: EasyjetHub/base-config.yaml

# Which analysis to consider
do_bbyy_analysis: true
# Decay mode considered for truth decoration
truthDecayModes: ["bbyy"]

# Toggles for object types
do_small_R_jets: true
do_muons: true
do_electrons: true
do_photons: true
do_met: true
do_KinematicFit: false

# Toggles for reconstructed objects decorations
small_R_jet:
  # btagging nominal working point
  btag_wp: "GN2v01_FixedCutBEff_77"
  # to use multiple btagging WPs
  btag_extra_wps:
    - GN2v01_Continuous
    #GN2v00NewAliasWP
    #DL1dv01

  amount: 4
  variables_int_allJets: ["truthLabel", "PassWP", "pcbt"]

Electron:
  ID: "MediumLH"
  Iso: "Loose_VarRad"

Muon:
  ID: "Medium"
  Iso: "PflowLoose_VarRad"

# photon ID and isolation requirements
Photon:
  ID: "Loose" # Loose, Tight
  Iso: "NonIso"
  amount: 2
  variables: ["ptOvermyy"]
  # The first extra wp is used for the final photon selections
  extra_wps: 
    - ["Tight", "FixedCutLoose"]
    - ["Tight", "NonIso"]
    - ["Loose", "FixedCutLoose"]

# orthogonality studies  
orthogonality:
  include: EasyjetHub/orth-config.yaml 
  do_orth_check: false # if set to true, this will just add more information to your output ntuple on whether events fall into HH-like categories - it will not remove events (assuming overlap removal including all objects does not have an impact on your analysis)

# list of triggers per year to consider
trigger:
  include: bbyyAnalysis/trigger.yaml

# apply loose jet cleaning only
loose_jet_cleaning: true

# write objects with overlap removal applied
do_overlap_removal: true

# Store high level variables by default 
# when the config file set the high level variables
store_high_level_variables: false

#Enable cutflow 
save_bbyy_cutflow: true
do_resonant_PNN: false

# flag that toggles single photon trigger in the cutflow
# so that PASS_TRIGGER = single || diphoton
enable_single_photon_trigger: false

# flag that toggles run-through mode in SelectorAlg
bypass: false

# flag for trigger filtering
do_trigger_filtering: false

# flag for event cleaning
do_event_cleaning: true

# name that will go in the tree bbyy_pass_<selection_name>_%SYS%
selection_name: "allcuts"

# bdt models used for categorisation and VBF jets selection
# They should appear in this order lowMass / highMass / VBF jets
BDT_path:
  - "bbyyAnalysis/bdt_legacy_lowMass.root"
  - "bbyyAnalysis/bdt_legacy_highMass.root"
  - "bbyyAnalysis/bdt_legacy_vbf_jets.root"

#  choose VBF jets selection method
VBFjetsMethod: "BDT" # "mjj" "pTsorting"
