include: bbyyAnalysis/RunConfig-Resonant-base.yaml

CutList :
      - PASS_TRIGGER
      - TWO_TIGHTID_ISO_PHOTONS
      - PASS_RELPT
      - EXACTLY_ZERO_LEPTONS
      - AT_LEAST_TWO_JETS
      - LESS_THAN_SIX_CENTRAL_JETS
      - EXACTLY_ONE_OR_TWO_B_JETS

do_CP_systematics: true
systematics_regex: ['JET_JER_EffectiveNP_*', 'EG_*'] # for now include only these systematics
        
ttree_output:
  include: bbyy-base-output.yaml

Small_R_jet:
  btag_wp: "GN2v01_FixedCutBEff_90"