include: EasyjetHub/base-config.yaml

# Toggles for object types
do_small_R_jets: true
do_large_R_Topo_jets: false
do_large_R_UFO_jets: false
do_VR_jets: false
do_muons: false
do_electrons: false
do_photons: true

# btagging working points for small Rjets
btag_wps:
    #- DL1r_FixedCutBEff_77
    #- DL1dv01_FixedCutBEff_70
    - DL1dv01_FixedCutBEff_77
    #- DL1dv01_FixedCutBEff_85
    #- GN120220509_FixedCutBEff_70
    #- GN120220509_FixedCutBEff_77
    #- GN120220509_FixedCutBEff_85

# btagging working points for Variable Radius Track jets
#vr_btag_wps:
    #- DL1r_FixedCutBEff_77
    #- DL1r_FixedCutBEff_85

PhotonWP: "Loose.NonIso"  # possibly make a list to try multiple photon WPs

# list of triggers to apply
# "Auto" configures mc from the r-tag, data from year, e.g. data22
trigger_year: Auto

# "Auto" configures triggers for "bbbbResolved", "bbbbBoosted"
# We can also be explicit here I think
trigger_list: ["HHyybb"]

# apply trigger lists to filter events
do_trigger_filtering: false

# disable CP Algs for calibration
disable_calib: false

# apply loose jet cleaning only
loose_jet_cleaning: true

# if you want to run a baseline diHiggs analyses
do_yybb_analysis: true

# if you want to truth match (is MC protected)
# Whether to activate CP alg systematic variations
do_CP_systematics: false
systematics_regex: [".*"]

# write objects with overlap removal applied
# turning this on you have to decide on one large R jet collection
do_overlap_removal: false

# configure TTree output contents
ttree_output:
  AnalysisMiniTree:
    reco_outputs:
      small_R_jets: true
      photons: true
    truth_outputs:
      small_R_jets: true
      higgs_particle: true
