include: EasyjetHub/base-config.yaml

# Which analysis and channels to consider
do_bbVV_analysis: true
channels: ["1leptonBoosted","1leptonSplitboosted","0leptonBoosted","0leptonSplitboosted"]

# Decay mode considered for truth decoration
Truth:
  decayModes: ["bbWW","bbZZ"]

# Toggles for object types
do_small_R_jets: true
do_large_R_UFO_jets: true
do_muons: true
do_electrons: true
do_met : true

# Toggles for reconstructed objects decorations
Small_R_jet:
  # btagging nominal working point
  btag_wp: "DL1dv01_FixedCutBEff_77"

Electron:
  ID: "LooseBLayerLH"
  Iso: "Loose_VarRad"
  extra_wps:
    - ["TightLH", "Loose_VarRad"]

Muon:
  ID: "Loose"
  Iso: "PflowLoose_VarRad"
  extra_wps:
    - ["Medium", "PflowLoose_VarRad"]

Lepton:
  amount: 1

# orthogonality studies  
orthogonality:
  include: EasyjetHub/orth-config.yaml 
  do_orth_check: false # if set to true, this will just add more information to your output ntuple on whether events fall into HH-like categories - it will not remove events (assuming overlap removal including all objects does not have an impact on your analysis)

# list of triggers per year to consider
Trigger:
  include: bbVVAnalysis/trigger.yaml

# write objects with overlap removal applied
# turning this on you have to decide on one large R jet collection
do_overlap_removal: true

# Include the TTree configuration and update details
ttree_output:
  include: EasyjetHub/AnalysisMiniTree-config.yaml
  # Our overrides. All defaults are off
  slim_variables_with_syst: true
  reco_outputs:
    small_R_jets: 'container_names.output.reco4PFlowJet'
    large_R_UFO_jets: 'container_names.output.reco10UFOJet'
    muons: 'container_names.output.muons'
    electrons: 'container_names.output.electrons'
    met : 'container_names.output.met'
  collection_options:
    small_R_jets:
      btag_info: true
  truth_outputs:
    small_R_jets: 'container_names.input.truth4Jet'
    higgs_particle: 'container_names.output.truthHHParticles'
