include: EasyjetHub/base-config.yaml

# Toggles for object types
do_small_R_jets: true
do_muons: true

# Decay mode considered for truth decoration
truthDecayModes: ["bbbb"]

# small R config
small_R:
  # nominal btagging working point, used for b-jet pT calibration in particular
  btag_wp: "DL1dv01_FixedCutBEff_77"
  # additional btagging working points, available for selections and per-jet SFs
  btag_extra_wps:
    - DL1dv01_FixedCutBEff_70
    - DL1dv01_FixedCutBEff_85
    - GN120220509_FixedCutBEff_70
    - GN120220509_FixedCutBEff_77
    - GN120220509_FixedCutBEff_85

# list of triggers per year to consider
trigger_chains:
  include: EasyjetHub/trigger.yaml

# apply loose jet cleaning only
loose_jet_cleaning: true

do_resolved_dihiggs: false
do_boosted_dihiggs: false

do_CP_systematics: true
systematics_regex: [".*"]
histograms: true
