include: [bbbbAnalysis/RunConfig-HH4b-All.yaml]

triggerSFBranchSaveStrategy: "both"
do_CP_systematics: false
systematics_regex: []

# Only dump gn3 scores for no-systematics runs
ttree_output:
  collection_options:
    small_R_jets:
      gn3_scores: true