include: EasyjetHub/base-config.yaml

# Which analysis to consider
do_resolved_dihiggs: false
do_boosted_dihiggs: false

# Decay mode considered for truth decoration
Truth:
  decayModes: ["bbbb"]

# Toggles for object types
do_small_R_jets: true
do_large_R_Topo_jets: false
do_large_R_UFO_jets: true
do_VR_jets: true
do_muons: true

# Toggles for reconstructed objects decorations
Small_R_jet:
  # nominal btagging working point, used for b-jet pT calibration in particular
  btag_wp: "DL1dv01_FixedCutBEff_77"
  # additional btagging working points, available for selections and per-jet SFs
  btag_extra_wps:
    - DL1dv01_FixedCutBEff_70
    - DL1dv01_FixedCutBEff_85

Muon:
  ID: "Loose"
  Iso: "PflowLoose_VarRad"

# orthogonality studies  
orthogonality:
  include: EasyjetHub/orth-config.yaml 
  do_orth_check: false # if set to true, this will just add more information to your output ntuple on whether events fall into HH-like categories - it will not remove events (assuming overlap removal including all objects does not have an impact on your analysis)

# list of triggers per year to consider
Trigger:
  include: bbbbAnalysis/triggers.yaml

# apply loose jet cleaning only
loose_jet_cleaning: true

# Include the TTree configuration and update details
ttree_output:
  include: EasyjetHub/AnalysisMiniTree-config.yaml
  # Our overrides. All defaults are off
  reco_outputs:
    small_R_jets: 'container_names.output.reco4PFlowJet'
    large_R_UFO_jets: 'container_names.output.reco10UFOJet'
    VR_jets: 'container_names.output.vrJet'
  collection_options:
    small_R_jets:
      truth_parent_info: true
      btag_info: true
      JVT_details: true
      no_bjet_calib_p4: true
      btag_details: true
    large_R_jets:
      truth_labels: true
  truth_outputs:
    small_R_jets: 'container_names.input.truth4Jet'
    large_R_jets: ['container_names.input.truth10TrimmedJet','container_names.input.truth10SoftDropJet']
    higgs_particle: 'container_names.output.truthHHParticles'

