.flake8_check_template: &flake8_check_template
  stage: linting
  image: python:3.8-slim
  before_script:
    - pip install flake8
  script:
    # Ignore some more annoying flake8 problems:
    #  E231: missing whitespace after comma, semicolon, colon
    #  E241: multiple spaces after comma (and at least colon)
    #  W503: line break before binary operator
    #  E741: ambiguous variable name
    - flake8 --ignore=E231,E241,W503,E741 . --per-file-ignores="hub.py:F401"
  needs: []

.black_check_template: &black_check_template
  stage: linting
  image: python:3.8-slim
  before_script:
    - pip install black==22.3.0
  script:
    - black --check .
  needs: []

.cppcheck: &cpp_check_template
  stage: linting
  image: atlas/athanalysis:22.2.55
  tags:
    - cvmfs
  before_script:
    - source /release_setup.sh
  script:
    - /cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/cppcheck/current/cppcheck*/bin/cppcheck --enable=warning,portability --xml-version=2 .
  needs: []

flake8:
  <<: *flake8_check_template

# black:
#   <<: *black_check_template

cppcheck:
  <<: *cpp_check_template

