variables:
  # overrides the log level in easyjet-test
  EASYJET_LOG_LEVEL: INFO
  # default test directory for easyjet-test, can be overridden by -d
  EASYJET_TESTDIR: ci_testdir

.ntupler:
  stage: run
  needs: [compile]
  artifacts:
    paths:
      - $EASYJET_TESTDIR/output-branches-analysis-variables.txt
      - $EASYJET_TESTDIR/userJobMetadata.json

ntupler_data18_fast:
  extends: .ntupler
  script:
    - easyjet-test data18-fast

ntupler_data22_fast:
  extends: .ntupler
  script:
    - easyjet-test data22-fast

ntupler_jets_mc20:
  extends: .ntupler
  script:
    - easyjet-test jets-mc20

ntupler_jets_mc20_fast:
  extends: .ntupler
  script:
    - easyjet-test jets-mc20-fast

ntupler_jets_mc23:
  extends: .ntupler
  script:
    - easyjet-test jets-mc23

ntupler_ttbar_mc20:
  extends: .ntupler
  script:
    - easyjet-test ttbar-mc20

ntupler_ttbar_mc20_fast:
  extends: .ntupler
  script:
    - easyjet-test ttbar-mc20-fast

ntupler_sh4b_boosted_mc20_fast:
  extends: .ntupler
  script:
    - easyjet-test sh4b-boosted-mc20-fast

ntupler_yybb_mc20:
  extends: .ntupler
  script:
    - easyjet-test yybb-mc20

ntupler_ttbar-mc21:
  extends: .ntupler
  script:
    - easyjet-test ttbar-mc21

ntupler_ttbar_mc21_fast:
  extends: .ntupler
  script:
    - easyjet-test ttbar-mc21-fast

ntupler_ttbar_mc21_syst:
  extends: .ntupler
  script:
    - easyjet-test ttbar-mc21-syst

ntupler_hh4b-mc21:
  extends: .ntupler
  script:
    - easyjet-test hh4b-mc21

ntupler_hh4b_mc21_noroot:
  extends: .ntupler
  script:
    - easyjet-test hh4b-mc21-noroot

ntupler_hh4b_mc21_syst:
  extends: .ntupler
  script:
    - easyjet-test hh4b-mc21-syst

ntupler_lite_hh4b_mc21:
  extends: .ntupler
  script:
    - easyjet-test lite-hh4b-mc21

ntupler_lite_hh4b-mc21_fast:
  extends: .ntupler
  script:
    - easyjet-test lite-hh4b-mc21-fast

ntupler_lite_sh4b_boosted_mc20:
  extends: .ntupler
  script:
    - easyjet-test lite-sh4b-boosted-mc20

ntupler_lite_sh4b_boosted_mc20_fast:
  extends: .ntupler
  script:
    - easyjet-test lite-sh4b-boosted-mc20-fast

ntupler_lite_yybb_mc20:
  extends: .ntupler
  script:
    - easyjet-test lite-yybb-mc20

ntupler_sh4b_boosted_mc20:
  extends: .ntupler
  script:
    - easyjet-test sh4b-boosted-mc20

ntupler_sh4b_boosted_mc20_p5658:
  extends: .ntupler
  script:
    - easyjet-test sh4b-boosted-mc20-p5658
