
run_VariableDumper_DAOD_PHYS:
  stage: run
  needs: [compile]
  script:
    - hh4b-test ntuple

run_VariableDumper_fast_DAOD_PHYS:
  stage: run
  needs: [compile]
  script:
    - hh4b-test ntuple-fast
