include: EasyjetHub/base-config.yaml

# Toggles for object types
do_small_R_jets: true
do_large_R_Topo_jets: false
do_large_R_UFO_jets: false
do_VR_jets: false
do_muons: true
do_electrons: true
do_photons: false

# Decay mode considered for truth decoration
truthDecayModes: ["bbbb"]

# small R config
small_R:
  btag_wp: DL1dv01_FixedCutBEff_77
    #- DL1dv01_FixedCutBEff_70
    #- DL1dv01_FixedCutBEff_77
    #- DL1dv01_FixedCutBEff_85
    #- GN120220509_FixedCutBEff_70
    #- GN120220509_FixedCutBEff_77
    #- GN120220509_FixedCutBEff_85

# list of triggers to apply
# "Auto" configures mc from the r-tag, data from year, e.g. data22
trigger_year: Auto

# list of triggers per year to consider
trigger_chains:
  include: ttHHAnalysis/trigger.yaml

# apply trigger lists to filter events
do_trigger_filtering: false

# disable CP Algs for calibration
disable_calib: false

# apply loose jet cleaning only
loose_jet_cleaning: true

# if you want to run a baseline diHiggs analyses
do_ttHH_analysis: true

# if you want to truth match (is MC protected)
# Whether to activate CP alg systematic variations
do_CP_systematics: false
systematics_regex: [".*"]

# write objects with overlap removal applied
# turning this on you have to decide on one large R jet collection
do_overlap_removal: false

#Enable cutflow 
do_ttHH_cutflow: true

# Include the TTree configuration and update details
ttree_output:
  - AnalysisMiniTree:
    include: EasyjetHub/AnalysisMiniTree-config.yaml
    # Our overrides. All defaults are off
    reco_outputs:
      small_R_jets: 'container_names.output.reco4PFlowJet'
      electrons: 'container_names.output.electrons'
      muons: 'container_names.output.muons'
    truth_outputs:
      small_R_jets: 'container_names.input.truth4Jet'
      higgs_particle: 'container_names.output.truthHHParticles'
