# Name the TTree
tree_name: AnalysisMiniTree
directory_name: ''
stream_name: ANALYSIS
# Do we apply object systs only for pt/et
write_object_systs_only_for_pt: false
# which objects to write
reco_outputs:
  small_R_jets: false
  large_R_Topo_jets: false
  large_R_UFO_jets: false
  VR_jets: false
  muons: false
  electrons: false
  photons: false
  taus: false
  met: false

collection_options:

  small_R_jets:
    higgs_parent_info: false
    btag_info: false
    JVT_details: false
    no_bjet_calib_p4: false
    gn2_branches: false

  large_R_jets:
    substructure_info: false
    truth_labels: false

# turned off automatically if MC
truth_outputs:
  small_R_jets: false
  large_R_jets: false
  higgs_particle: false
# custom extra output branches
extra_output_branches: []
