include: base-config.yaml

# Toggles for object types
do_small_R_jets: true
do_large_R_UFO_jets: true
do_muons: true

# btagging working points for small Rjets
btag_wps:
    - DL1dv01_FixedCutBEff_70
    - DL1dv01_FixedCutBEff_77
    - DL1dv01_FixedCutBEff_85
    - GN120220509_FixedCutBEff_70
    - GN120220509_FixedCutBEff_77
    - GN120220509_FixedCutBEff_85

# btagging working points for Variable Radius Track jets
vr_btag_wps:
    - DL1r_FixedCutBEff_77
    - DL1r_FixedCutBEff_85

# "Auto" configures triggers for "bbbbResolved", "bbbbBoosted"
# We can also be explicit here I think
trigger_list: ["bbbbResolved", "bbbbBoosted"]

# apply trigger lists to filter events
do_trigger_filtering: true

# disable CP Algs for calibration
disable_calib: true

# apply loose jet cleaning only
loose_jet_cleaning: true

# which objects to write
write_small_R_jets: true
write_large_R_UFO_jets: true
write_muons: true

# additional small R info
write_small_R_higgs_parent_info: true
write_small_R_gn2_branches: true

# additional Large R info
write_large_R_substructure: true

# turned off automatically if MC
write_truth_small_R_jets: true
write_truth_large_R_jets: true
write_truth_higgs: true

# custom extra output branches
extra_output_branches: []
